services:
  redis:
    image: redis:7.0.4
    ports:
      - "6379:6379"

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
  
  celery:
    build: .
    working_dir: /code/imageprocessing
    command: celery -A imageprocessing worker --loglevel=info
    env_file:
      - .env 
    volumes:
      - .:/code 
    depends_on:
      - redis
      - rabbitmq

  db:
    image: postgres:14.5
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  web:
    build: .
    command: python imageprocessing/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq